name: Nicolas
favicon: null
layout_spectrum: 0.8172043
typography_spectrum: 0.1003584
title: "\"Do, or do not... There's no try.\" - Yoda"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#667765'
    - '#18201D'
    - '#76A5AC'
    - '#E9D8D8'
    - '#CFA387'
  brandStrength: 1
  lightness: 0.611405
  saturation: 0.2405342
  rhythmicContrast: 0.7741935
purpose: []
